### ISSUE TITLE
Report summary tables & Add non-Gaussian examples

### ISSUE THREAD

**Issue by yunanwu123** [PhilBoileau/cvCovEst#53]
- The plot.cvCovEst function reports the eigenvalues plot, risk plot, heatmap plot and the summary table with the best performing estimator within each class. The first three plots can be exported separately. Is it possible to output the summary table (in latex format, or other formats) separately? I believe it would be useful in presenting the analysis results. You could use "xtable" or other packages.
- It would be more convincing to add a non-Gaussian example in the reports, such as Gamma distributions.
- A typo: the argument in plot.cvCovEst for data is "dat_orig". However, in the **_Toy Dataset Example_** in your paper, it is "data_in".

**Comment by PhilBoileau** [comment]
Thank you for these suggestions! I'll address them in order:

1. That's a good idea. I've updated `summary.cvCovEst()` to return a `tibble` when a single summarization function is specified by the `summ_fun` argument. Users can now pass this `tibble` to the presentation function of their choice, (e.g. `xtable::xtable()`, `knitr::kable()`, etc). I've avoided implementing a specific table formatting function so that users have more flexibility. 
2. Employing Gaussian data, which is familiar to most, seems reasonable for illustration purposes. We also provide a real-data example. If readers remain unconvinced, they can review our [preprint](https://arxiv.org/abs/2102.09715) on the method. A much more comprehensive simulation study is performed in this work.
3. Thank you for your sharp eye. It's been fixed.

Thank you for reviewing our software! Please let me know if there is anything else that you would like me address.
